# Dockerizing AnonymousUpload: Dockerfile for building Solr 4.7.2 images
# Based on centos:centos6

FROM centos:centos6

RUN yum install -y java-1.7.0-openjdk.x86_64 java-1.7.0-openjdk-devel.x86_64 tar vi

RUN mkdir -p /opt

WORKDIR /opt

RUN curl -OL http://dl.bintray.com/vertx/downloads/vert.x-2.1.tar.gz

RUN tar -zxf vert.x-2.1.tar.gz

RUN rm -f vert.x-2.1.tar.gz

WORKDIR /usr/bin

RUN ln -s /opt/vert.x-2.1/bin/vertx .

RUN mkdir /opt/anonymousupload

# vertx runmod com.m3958.apps~anonymousupload~0.0.1-SNAPSHOT

# set vertx JAVA_HOME,/usr/lib/jvm/jre-1.7.0-openjdk.x86_64
